### ISSUE TITLE
TypeScript types declaration file

### ISSUE THREAD

**Issue by geopic** [Lakitna/cli-diagram#7]
Hello, I saw your post on Reddit and thought this package could use a types declaration file so that TypeScript developers are able to utilise it when developing a project with this package. Let me know if you'd like one and I can make one for you.

**Comment by Lakitna** [comment]
Sounds good!

Right now it's seriously lacking typing details. I'm planning to add jsdoc strings with typing information in 0.2.0. I've already worked on this a bit, but that branch is currently only on my machine at home.

I always like contributions, so if you want to you can start doing this. You can also wait a bit on the type docstrings, that would probably make your life easier :)

**Comment by geopic** [comment]
Sounds great @Lakitna, I'll wait until you push the jsdoc info and then I'll get started. :stars:

**Comment by Lakitna** [comment]
I've added the jsdocs to the public interface. You can find them in #10. 

I'll add the internal stuff later in the same branch.

**Comment by geopic** [comment]
So just to be clear, what do you mean by "internal stuff"?

**Comment by Lakitna** [comment]
At the moment I've added docstrings to the classes Diagram and most of Line.

The way I've build it the only directly front-facing class is Diagram. The rest is used internally by Diagram or extended by other classes.

For Typescript support, you probably only need to add full types for Diagram.
